apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "olc-rest-proxy.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "olc-rest-proxy.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "olc-rest-proxy.name" . }}
    spec:
      {{- if .Values.image.credentials }}
      imagePullSecrets:
        - name: {{ .Values.image.credentials }}
      {{- end }}
      containers:
        - name: {{ include "olc-rest-proxy.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["java", "-jar", "application.jar"]
          workingDir: /application
          ports:
            - containerPort: {{ .Values.service.port }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - CAP_NET_RAW
            runAsUser: 1001
          {{/*
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.liveness.path }}
              port: {{ .Values.service.port }}
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.liveness.failureThreshold }}
          */}}
          readinessProbe:
            httpGet:
              path: "/manage/health"
              port: {{ .Values.service.port }}
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.readiness.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.readiness.failureThreshold }}
          env:
            - name: SPRING_DATASOURCE_URL
              value: {{ .Values.env.SPRING_DATASOURCE_URL | quote }}         
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "olc-rest-proxy.fullname" . }}-secret
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "olc-rest-proxy.fullname" . }}-secret
                  key: SPRING_DATASOURCE_PASSWORD
